import Avengers from '../assets/Books/Avengers.jpg';
import Bat from '../assets/Books/Batman.avif';
import AB from '../assets/Books/Atomic Habits.jpg';
import Spider from '../assets/Books/Superior Spider-Man.jpeg';
import Dune from '../assets/Books/Dune.jpeg';
import GOT from '../assets/Books/GOT.jpeg';
import Harry from '../assets/Books/HP HBP.jpeg';
import J3 from '../assets/Books/Joker.avif';
import Loki from '../assets/Books/Loki.jpg';
import LOR from '../assets/Books/Lord of the Rings.jpg';
import RDPD from '../assets/Books/RDPD.jpg';
import LP from '../assets/Books/The Little Prince.jpeg';
import Thiru from '../assets/Books/Thirukkural.jpg';
import Thol from '../assets/Books/Tholkaappiyam.webp';
import ProfBoy from '../assets/Images/boy.webp'
export const reviews=[
    {name:'Nobita',revi:'Good'},
    {name:'Stark',revi:'Awesome'},
    {name:'Clark',revi:'Nice'},
];
export const Books=
[
    {name:'திருக்குறள்',Image:Thiru,Description:"திருக்குறள், சுருக்கமாகக் குறள் (ஆங்கிலம்: Tirukkuṟaḷ), ஒரு தொன்மையான தமிழ் மொழி அற இலக்கியமாகும். சங்க இலக்கிய வகைப்பாட்டில் பதினெண்கீழ்க்கணக்கு எனப்படும் பதினெட்டு நூல்களின் திரட்டில் இருக்கும் இந்நூல் குறள் வெண்பா என்னும் பாவகையினாலான 1,330 ஈரடிச் செய்யுள்களைக் கொண்டது.இந்நூல் முறையே அறம், பொருள், காமம் (அல்லது இன்பம்) ஆகிய மூன்று பகுப்புகளை அல்லது தொகுப்புகளைக் கொண்டது.இஃது அடிப்படையில் ஒரு வாழ்வியல் நூல். மாந்தர்கள் தம் அகவாழ்விலும் சுமூகமாகக் கூடி வாழவும் புற வாழ்விலும் இன்பமுடனும் இசைவுடனும் நலமுடனும் வாழவும் தேவையான அடிப்படைப் பண்புகளை விளக்குகிறது. அறநெறிகளைப் பற்றிய உலகின் மிகச்சிறந்த படைப்புகளில் ஒன்றாகக் கருதப்படும் இந்நூல், பொதுத்தன்மைக்கும் மதச்சார்பற்ற தன்மைக்கும் பெயர் பெற்றது.இதனை இயற்றியவர் திருவள்ளுவர் என்று பாரம்பரியமாக அறியப்படுகிறார். இந்நூலின் காலம் பொ.ஊ.மு. 300 முதல் பொ.ஊ. 5-ம் நூற்றாண்டு வரை எனப் பலவாறு கணிக்கப்படுகிறது.இந்நூல்,தனிநபர் அடிப்படை நல்லொழுக்கங்களாக இன்னா செய்யாமை, வாய்மை, கருணை, அன்பு, பொறுமை, சுயகட்டுப்பாடு, நன்றியுணர்வு, கடமை, சான்றாண்மை, ஈகை, விருந்தோம்பல், இல்வாழ்க்கை நலம், பரத்தையரோடு கூடாமை, கள்ளாமை, மது உள்ளிட்ட போதைப்பொருட்களையும் சூதாடுவதையும் தவிர்த்தல், கூடாஒழுக்கங்களை விலக்குதல் முதலிய அனைத்துத் தனிநபர் ஒழுக்கங்களையும் போதித்துக்கூடுதலாக ஆட்சியாளர் மற்றும் அமைச்சர்களின் ஒழுக்கங்கள், சமூகநீதி, அரண், போர், கொடியோருக்குத் தண்டனை, கல்வி, உழவு போன்ற பலவிதமான அரசியல் மற்றும் சமூகத் தலைப்புகளை உள்ளடக்கியது.மேலும் நட்பு, காதல், தாம்பத்தியம் மற்றும் அகவாழ்க்கை பற்றிய அதிகாரங்களும் இதில் அடங்கும். சங்ககாலத் தமிழரிடையே காணப்பட்ட குற்றங்களையும் குறைகளையும் மறுத்துரைத்து அவர்தம் பண்பாட்டு முரண்களைத் திருத்தியும் பிழைப்பட்ட வாழ்வியலை மாற்றியும் தமிழ்க் கலாச்சாரத்தினை நிரந்தரமாக வரையறை செய்த நூலாகத் திருக்குறள் திகழ்கிறது.இயற்றப்பட்ட காலத்திலிருந்து குறள் அற, சமூக, அரசியல், பொருளாதார, மத, தத்துவ மற்றும் ஆன்மீகத் துறைகளைச் சார்ந்த அறிஞர்களாலும் தலைவர்களாலும் பரவலாகப் போற்றப்பட்டு வந்துள்ளது.",reviews},
    {name:'Avengers',Image:Avengers,Description:'The Avengers are a team of superheroes appearing in American comic books published by Marvel Comics, created by writer-editor Stan Lee and artist/co-plotter Jack Kirby. The team made its debut in The Avengers #1 (cover-dated September 1963). Labeled Earth\'s Mightiest Heroes, the original Avengers consisted of Iron Man, Ant-Man, Hulk, Thor and the Wasp. Captain America was discovered trapped in ice in issue #4, and joined the group after they revived him.',reviews},
    {name:'Batman Who Laughs',Image:Bat,Description:"The Batman Who Laughs (Bruce Wayne) is a supervillain appearing in American comic books published by DC Comics. He is the evil counterpart and alternate version of Batman within the Dark Multiverse.He is depicted as a hybrid of both Batman (Bruce Wayne) and Batman's arch enemy Joker, and is a member of the Dark Knights and the overarching antagonist of the Dark Multiverse Saga, alongside cosmic deities Perpetua and Barbatos, from 2017 to 2021, following DC Rebirth. His first appearance was in the crossover storyline Dark Nights: Metal, before receiving his own series and serving as the main antagonist in Batman/Superman in 2019 and DC Comics Year of the Villain alongside Lex Luthor.He was created by Scott Snyder and Greg Capullo. His name is an allusion both to the original Batman’s seriousness and to the 1928 film The Man Who Laughs featuring Conrad Veidt, by whose performance the Joker is inspired.",reviews},
    {name:'Three Jokers',Image:J3,Description:"Batman: Three Jokers is an American comic book limited series published by DC Comics. It is a spiritual successor to Batman: The Killing Joke and Batman: A Death in the Family. The three-issue storyline was written by Geoff Johns and illustrated by Jason Fabok and Brad Anderson, began in August and concluded in October 2020. In Three Jokers, Batman, Batgirl and Red Hood follow a lead on the Joker, who appears to have been three different men all along.The Three Jokers storyline was published under DC Black Label, an imprint allowing writers to present unique takes on DC characters for a mature audience. The storyline received positive reviews with praise for the art, story and character development despite criticism on the underdevelopment on Red Hood and Batgirl's story.",reviews},
    {name:'Dune',Image:Dune,Description:"Dune, also known as the Dune Chronicles, is an American science fiction media franchise that originated with the 1965 novel Dune by Frank Herbert[a] and has continued to add new publications. Dune is frequently described as the best-selling science fiction novel in history.It won the inaugural Nebula Award for Best Novel and the Hugo Award in 1966, and was later adapted into a 1984 film, a 2000 television miniseries, and a 2021 film. Herbert wrote five sequels, the first two of which were concomitantly adapted as a 2003 miniseries. Dune has also inspired tabletop games and a series of video games. Since 2009, the names of planets from the Dune novels have been adopted for the real-world nomenclature of plains and other features on Saturn's moon Titan.Frank Herbert died in 1986. Beginning in 1999, his son Brian Herbert and science fiction author Kevin J. Anderson published several collections of prequel novels, as well as two sequels that complete the original Dune series (Hunters of Dune in 2006 and Sandworms of Dune in 2007), partially based on Frank Herbert's notes discovered a decade after his death.",reviews},
    {name:'Atomic Habits',Image:AB,Description:"Atomic Habits by James Clear is a comprehensive, practical guide on how to change your habits and get 1% better every day. Using a framework called the Four Laws of Behavior Change, Atomic Habits teaches readers a simple set of rules for creating good habits and breaking bad ones. Read the full summary to glean 3 key lessons from Atomic Habits, learn how to build a habit in 4 simple steps, and get a handy reference guide for the strategies recommended throughout the book.",reviews},
    {name:'Superior Spider-Man',Image:Spider,Description:"Superior Spider-Man is one of the biggest Spider-Man stories to thwip through the pages of Marvel Comics in recent years -- it's also a complicated web of a tale! A dying Otto Octavius AKA Doctor Octopus takes over Peter Parker's body to become his own version of our friendly neighborhood Spider-Man? What happens to Peter? Is Superior Spider-Man even friendly? Spider-bots This is where Long Story Short comes in, a new digital series that gives Marvel fans the nutshell version of some of Marvel's greatest comic stories. From the very beginning of the Superior Spider-Man story in AMAZING SPIDER-MAN #700 to 2013's SUPERIOR SPIDER-MAN series, you can read the whole arc on Marvel Unlimited!",reviews},
    {name:'Game Of Thrones',Image:GOT,Description:"Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing. The cold is returning, and in the frozen wastes to the north of Winterfell, sinister forces are massing beyond the kingdom’s protective Wall. To the south, the king’s powers are failing—his most trusted adviser dead under mysterious circumstances and his enemies emerging from the shadows of the throne. At the center of the conflict lie the Starks of Winterfell, a family as harsh and unyielding as the frozen land they were born to. Now Lord Eddard Stark is reluctantly summoned to serve as the king’s new Hand, an appointment that threatens to sunder not only his family but the kingdom itself.Sweeping from a harsh land of cold to a summertime kingdom of epicurean plenty, A Game of Thrones tells a tale of lords and ladies, soldiers and sorcerers, assassins and bastards, who come together in a time of grim omens. Here an enigmatic band of warriors bear swords of no human metal; a tribe of fierce wildlings carry men off into madness; a cruel young dragon prince barters his sister to win back his throne; a child is lost in the twilight between life and death; and a determined woman undertakes a treacherous journey to protect all she holds dear. Amid plots and counter-plots, tragedy and betrayal, victory and terror, allies and enemies, the fate of the Starks hangs perilously in the balance, as each side endeavors to win that deadliest of conflicts: the game of thrones.",reviews},
    {name:'Harry Potter Half-Blood Prince',Image:Harry,Description:"Harry Potter and the Half-Blood Prince is a fantasy novel written by British author J. K. Rowling and the sixth and penultimate novel in the Harry Potter series. Set during Harry Potter's sixth year at Hogwarts, the novel explores the past of the boy wizard's nemesis, Lord Voldemort, and Harry's preparations for the final battle against Voldemort alongside his headmaster and mentor Albus Dumbledore.The book was published in the United Kingdom by Bloomsbury and in the United States by Scholastic on 16 July 2005, as well as in several other countries. It sold almost seven million copies in the first 24 hours after its release, a record eventually broken by its sequel, Harry Potter and the Deathly Hallows.There were many controversies before and after it was published, including the right-to-read copies delivered before the release date in Canada. Reception to the novel was generally positive, and it won several awards and honours, including the 2006 British Book of the Year award.Reviewers noted that the book had a darker tone than its predecessors, though it did contain some humour. Some considered the main themes love, death, trust, and redemption. The considerable character development of Harry and many other teenage characters also drew attention.",reviews},
    {name:'Loki',Image:Loki,Description:"Loki Laufeyson is a character appearing in American comic books published by Marvel Comics. Created by writer Stan Lee, scripter Larry Lieber, and penciller Jack Kirby, the character first appeared in Venus #6 (August 1949), although the characterization that has persisted to the modern day debuted in Journey into Mystery #85 (October 1962).The character, which is based on the Norse deity of the same name, is the Asgardian God of Mischief, the adopted son of Odin and the adopted brother of the superhero Thor. Loki has been portrayed as both a supervillain and antihero.Loki has appeared in several ongoing series, limited series and alternate reality series, including the 4-issue series Loki in 2004 and 2006, being the main character of Journey into Mystery from issues 622 to 645, appearing in new issues of Young Avengers in 2013 and receiving four more solo series, Loki: Agent of Asgard in 2013, Vote Loki in 2016, Loki in 2019 and Loki in 2023.",reviews},
    {name:'The Little Prince',Image:LP,Description:"The Little Prince (French: Le Petit Prince, pronounced [lə p(ə)ti pʁɛ̃s]) is a novella written and illustrated by French aristocrat, writer, and military pilot Antoine de Saint-Exupéry. It was first published in English and French in the United States by Reynal & Hitchcock in April 1943 and was published posthumously in France following liberation; Saint-Exupéry's works had been banned by the Vichy Regime. The story follows a young prince who visits various planets, including Earth, and addresses themes of loneliness, friendship, love, and loss. Despite its style as a children's book, The Little Prince makes observations about life, adults, and human nature.The Little Prince became Saint-Exupéry's most successful work, selling an estimated 140 million copies worldwide, which makes it one of the best-selling in history.The book has been translated into over 505 different languages and dialects worldwide, being the second most translated work ever published, trailing only the Bible.The Little Prince has been adapted to numerous art forms and media, including audio recordings, radio plays, live stage, film, television, ballet, and opera.",reviews},
    {name:'Lord of the Rings',Image:LOR,Description:"The Lord of the Rings, fantasy novel by J.R.R. Tolkien initially published in three parts as The Fellowship of the Ring (1954), The Two Towers (1955), and The Return of the King (1955). The novel, set in the Third Age of Middle-earth, formed a sequel to Tolkien’s The Hobbit (1937) and was succeeded by his posthumous The Silmarillion (1977). The Lord of the Rings is the saga of a group of sometimes reluctant heroes who set forth to save their world from consummate evil. Its many worlds and creatures were drawn from Tolkien’s extensive knowledge of philology and folklore.At 33, the age of adulthood among hobbits, Frodo Baggins receives a magic Ring of Invisibility from his uncle Bilbo. Frodo, a Christlike figure, learns that the ring has the power to control the entire world and, he discovers, to corrupt its owner. A fellowship of hobbits, elves, dwarfs, and men is formed to destroy the ring by casting it into the volcanic fires of the Crack of Doom, where it was forged. They are opposed on their harrowing mission by the evil Sauron and his Black Riders.",reviews},
    {name:'Rich Dad Poor Dad',Image:RDPD,Description:"It's been nearly 25 years since Robert Kiyosaki’s Rich Dad Poor Dad first made waves in the Personal Finance arena.It has since become the #1 Personal Finance book of all time... translated into dozens of languages and sold around the world.Rich Dad Poor Dad is Robert's story of growing up with two dads  his real father and the father of his best friend, his rich dad  and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.20 Years... 20/20 Hindsight In the 20th Anniversary Edition of this classic, Robert offers an update on what we’ve seen over the past 20 years related to money, investing, and the global economy. Sidebars throughout the book will take readers fast forward”  from 1997 to today  as Robert assesses how the principles taught by his rich dad have stood the test of time.",reviews},
    {name:'தொல்காப்பியம்',Image:Thol,Description:"தொல்காப்பியம் (ஆங்கில மொழி: Tolkāppiyam) என்பது இன்று கிடைக்கப்பெறும் மிக மூத்த தமிழ் இலக்கண நூலாகும். இஃது இலக்கிய வடிவிலிருக்கும் ஓர் இலக்கண நூலாகும். இந்நூலை இயற்றியவர் தொல்காப்பியர் என்று தொல்காப்பியப் பாயிரத்தில் குறிப்பிடப் பட்டுள்ளது. தொல்காப்பியத்தில் இடைச்செருகல்கள் உள்ளதாக அறிஞர்கள் கருதுகின்றனர். பழங்காலத்து நூலாக இருப்பினும், இன்றுவரை தமிழ் இலக்கண விதிகளுக்கு அடிப்படையான நூல் இதுவேயாகும்.தொல்காப்பியத்தை முதல்நூலாகக் கொண்டு காலந்தோறும் பல வழிநூல்கள் தோன்றின.தொல்காப்பிய நூலுக்கு சிறப்புப் பாயிரம் இயற்றியவர் பனம்பாரனார். இவர் தொல்காப்பியர் உடன் பயின்றவர். இது பாணினி எழுதிய வடமொழி இலக்கண நூலுக்கு சமகாலத்து நூல்கள். தொல்காப்பியர் காலத்தில் தமிழில் இருந்த 'முந்துநூல்' (அகத்தியமும்) கண்டிருந்தார். தோற்றம் என்ற தலைப்பில் சான்றுடன் கூடிய தொல்காப்பியர் காலம் இணைக்கப்பட்டுள்ளது. செம்மொழித் தமிழாய்வு மத்திய நிறுவனம் தொல்காப்பியர் ஆண்டினை பொ.ஊ.மு. 711 என்று பொருத்தியது.",reviews}
];
export const showcase=
[
    {name:'திருக்குறள்',Image:Thiru},
    {name:'Three Jokers',Image:J3},
    {name:'Loki',Image:Loki},
    {name:'The Little Prince',Image:LP},
    {name:'Rich Dad Poor Dad',Image:RDPD}
]

export const profImg=
{
    Img:ProfBoy
}